### ISSUE TITLE
champ.DMP error when only one significant DMP is found

### ISSUE THREAD

**Issue by TobiTekath** [YuanTian1991/ChAMP#2]
Hi Joshua,

when Champ only finds one significant MVP it creates an error in 

> Section 3: Match Annotation Start:

```
Error in rowMeans(beta[com.idx, which(pheno == Compare[[i]][1])]) : 
  'x' must be an array of at least two dimensions
```
Best
Tobi

**Comment by JoshuaTian** [comment]
Hello Tobi, this is a small bug, I noticed it already. Previously, if I encounter this problem in data analysis, I will looser the adjPval parameter, then allow more DMPs get detected, but I will modify this in future version.

And sorry for the late reply, I don't know why Github never remind me any message.

**Comment by As-giotto** [comment]
I have the same problem

**Comment by As-giotto** [comment]
> Hello Tobi, this is a small bug, I noticed it already. Previously, if I encounter this problem in data analysis, I will looser the adjPval parameter, then allow more DMPs get detected, but I will modify this in future version.
> 
> And sorry for the late reply, I don't know why Github never remind me any message.

I have the same problem
